#!/bin/bash
# Author: ld0
# Version 3.0
# TODO:
#	1. make conversion to video take in .wav 
#	2. allow for ogg input file conversion 
#	3. delete temporary file created if audio conversion takes place
#

#
# /.makevids $1 $2 $3
#	$1 = image desired to have the video feature as its only image
#	$2 = audio file desired to have the video feature.
#				v.1.0 	mp3 only
#				v.2.0+	mp3 or wav
#	$3 = desired output file name
#
if [ "$#" -ge 2 ]
then
        
        in_img=$1
        in_audio=$2
        out_vid="$3.mp4"
        if [ "$#" -eq 2 ]
        then
			out_vid=${in_audio::-3}"mp4"
        fi
        echo $out_vid
        exit
        ext=${in_audio: (-3) } # get file extension
        
        # convert to mp3 if it's wav file
        if [ $ext == "wav" ]
        then
			new_audio=${in_audio::-3}"mp3"
			ffmpeg -i $in_audio -vn -ar 44100 -ac 2 -ab 192k -f mp3 $new_audio
			
        fi
        
        in_audio=${in_audio::-3}"mp3"
		# smallest video possible 
        ffmpeg -r 1 -loop 1 -i $in_img -i $in_audio -acodec copy -r 1 -shortest -vf scale=1280:720 $out_vid

# Print out help menu
elif [[ "$1" = "-h" || "$1" = "-help" ]]
then
	echo -e "\tConvert mp3 or wav files to mp4 video with ffmpeg"				# -e used to allow for tab indentation for readability
	echo -e "\tSyntax: ./makevids image_file audio_file (optional out_file)"
	echo -e "\tIf out_file not specified, default will be audio_file.mp4"

# elif there weren't enough arguments
else
        echo "Incorrect number of arguments. image audio {optional outname}"
fi
